on:
  push:
    tags:
      - "v*"
name: Create release

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: process-description.tex
      - name: Release PDF
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.pdf
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
